// Generated by tools/contracts-build.ts; do not edit.
import type { Config, LegacyConfig } from './config.ts';
export declare function validateConfig(value: unknown): value is Config;
export declare function validateLegacyConfig(
  value: unknown,
): value is LegacyConfig;
