// Generated by tools/contracts-build.ts; do not edit.
import type { DashboardStore, ShareTunnelStore } from './stores.ts';
export declare function validateDashboard(
  value: unknown,
): value is DashboardStore;
export declare function validateLegacyDashboard(value: unknown): boolean;
export declare function validateShareTunnel(
  value: unknown,
): value is ShareTunnelStore;
export declare function validateLegacyShareTunnel(value: unknown): boolean;
export declare function validateJournalHeader(value: unknown): boolean;
export declare function validateSpoolHeader(value: unknown): boolean;
