import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Ajv } from 'ajv';
import openapiTS, { astToString } from 'openapi-typescript';
import { cliSchemas } from '../lib/contracts/cli.ts';
import { ConfigLegacy, ConfigV1 } from '../lib/contracts/config.ts';
import { entitySchemas } from '../lib/contracts/entities.ts';
import { JsonValue, pilotSchemas } from '../lib/contracts/pilot.ts';
import { storeSchemas } from '../lib/contracts/stores.ts';

const root = fileURLToPath(new URL('../', import.meta.url));
const standaloneCode = createRequire(import.meta.url)(
  'ajv/dist/standalone/index.js',
) as typeof import('ajv/dist/standalone/index.js').default;
export function configOutputs(): Record<string, string> {
  const outputs: Record<string, string> = {};
  for (const [name, schema] of Object.entries({
    JsonValue,
    ConfigLegacy,
    ConfigV1,
  }))
    outputs[`contracts/dist/${name}.schema.json`] =
      `${JSON.stringify(schema, null, 2)}\n`;
  // Runtime file readers and copied render helpers must not resolve TypeBox,
  // Ajv, or a sibling MCP node_modules. Compile the canonical schemas to ESM.
  const ajv = new Ajv({
    strict: true,
    coerceTypes: false,
    useDefaults: false,
    removeAdditional: false,
    code: { source: true, esm: true },
  });
  ajv.addSchema(JsonValue).addSchema(ConfigLegacy).addSchema(ConfigV1);
  const validator = standaloneCode(ajv, {
    validateConfig: 'ConfigV1',
    validateLegacyConfig: 'ConfigLegacy',
  });
  if (/\b(?:require\s*\(|import\s*(?:\(|["'{*]))/.test(validator))
    throw new Error(
      'config standalone validator has an external runtime dependency',
    );
  outputs['lib/contracts/config-validator.js'] =
    `// Generated by tools/contracts-build.ts; do not edit.\n${validator}\n`;
  outputs['lib/contracts/config-validator.d.ts'] = [
    '// Generated by tools/contracts-build.ts; do not edit.',
    "import type { Config, LegacyConfig } from './config.ts';",
    'export declare function validateConfig(value: unknown): value is Config;',
    'export declare function validateLegacyConfig(',
    '  value: unknown,',
    '): value is LegacyConfig;',
    '',
  ].join('\n');
  for (const schema of Object.values(storeSchemas)) {
    outputs[`contracts/dist/${schema.$id}.schema.json`] =
      `${JSON.stringify(schema, null, 2)}\n`;
  }
  const storesAjv = new Ajv({
    strict: true,
    coerceTypes: false,
    useDefaults: false,
    removeAdditional: false,
    code: { source: true, esm: true },
  });
  storesAjv.addSchema(JsonValue);
  for (const schema of Object.values(storeSchemas)) storesAjv.addSchema(schema);
  const compiled = standaloneCode(storesAjv, {
    validateDashboard: 'DashboardV1',
    validateLegacyDashboard: 'DashboardLegacy',
    validateShareTunnel: 'ShareTunnelV1',
    validateLegacyShareTunnel: 'ShareTunnelLegacy',
    validateJournalHeader: 'JournalHeader',
    validateSpoolHeader: 'SpoolHeader',
  });
  if (/\b(?:require\s*\(|import\s*(?:\(|["'{*]))/.test(compiled))
    throw new Error('store validator has an external runtime dependency');
  outputs['lib/contracts/store-validator.js'] =
    `// Generated by tools/contracts-build.ts; do not edit.\n${compiled}\n`;
  outputs['lib/contracts/store-validator.d.ts'] = [
    '// Generated by tools/contracts-build.ts; do not edit.',
    "import type { DashboardStore, ShareTunnelStore } from './stores.ts';",
    'export declare function validateDashboard(',
    '  value: unknown,',
    '): value is DashboardStore;',
    'export declare function validateLegacyDashboard(value: unknown): boolean;',
    'export declare function validateShareTunnel(',
    '  value: unknown,',
    '): value is ShareTunnelStore;',
    'export declare function validateLegacyShareTunnel(value: unknown): boolean;',
    'export declare function validateJournalHeader(value: unknown): boolean;',
    'export declare function validateSpoolHeader(value: unknown): boolean;',
    '',
  ].join('\n');
  return outputs;
}
export async function contractOutputs(): Promise<Record<string, string>> {
  // Native child starts the actual private Fastify/SQLite route graph; Swagger
  // uses registered schemas, not a second hand-authored OpenAPI document.
  const { runScript } = await import('../test/support/run-script.mjs');
  const result = await runScript('test/fixtures/w3-openapi-export.mjs');
  const openapi = JSON.parse(result.stdout);
  const outputs: Record<string, string> = configOutputs();
  for (const [name, schema] of Object.entries({
    ...pilotSchemas,
    ...cliSchemas,
    JsonValue,
  }))
    outputs[`contracts/dist/${schema.$id ?? name}.schema.json`] =
      `${JSON.stringify(schema, null, 2)}\n`;
  for (const schema of Object.values(entitySchemas))
    outputs[`contracts/dist/${schema.$id}.schema.json`] =
      `${JSON.stringify(schema, null, 2)}\n`;
  outputs['contracts/dist/openapi.json'] =
    `${JSON.stringify(openapi, null, 2)}\n`;
  const typedPilot = {
    ...openapi,
    paths: Object.fromEntries(
      Object.entries(openapi.paths)
        .filter(([key]) => key === '/api/health' || key === '/api/tickets')
        .map(([key, methods]) => [
          key,
          key === '/api/tickets'
            ? { post: (methods as Record<string, unknown>).post }
            : methods,
        ]),
    ),
  };
  const apiTypes = astToString(await openapiTS(typedPilot));
  outputs['dashboard/web/src/api/types.d.ts'] = apiTypes;
  outputs['lib/contracts/pilot-api.d.ts'] = apiTypes;
  outputs['lib/pilot-client.ts'] = [
    '// Generated from contracts/dist/openapi.json by tools/contracts-build.ts.',
    "import createClient from 'openapi-fetch';",
    "import type { paths } from './contracts/pilot-api.d.ts';",
    '',
    'type CreateTicketBody =',
    "  paths['/api/tickets']['post']['requestBody']['content']['application/json'];",
    'const failed = (response: Response, payload: unknown, path: string) => {',
    "  throw Object.assign(new Error(response.status + ' ' + response.statusText + ' ' + path), { payload });",
    '};',
    'export function createPilotClient(baseUrl: string, fetchImpl: typeof fetch = globalThis.fetch) {',
    '  const client = createClient<paths>({ baseUrl, fetch: fetchImpl });',
    '  return {',
    '    async health() {',
    "      const { data, error, response } = await client.GET('/api/health');",
    '      if (!response.ok || data === undefined) return failed(response, error, `/api/health`);',
    '      return data;',
    '    },',
    '    async createTicket(body: CreateTicketBody) {',
    "      const { data, error, response } = await client.POST('/api/tickets', { body });",
    '      if (!response.ok || data === undefined) return failed(response, error, `/api/tickets`);',
    '      return data;',
    '    },',
    '  };',
    '}',
    '',
  ].join('\n');
  return outputs;
}
export function assertContractFreshness(
  outputs: Record<string, string>,
  base = root,
): void {
  const stale = Object.entries(outputs)
    .filter(
      ([file, content]) =>
        !fs.existsSync(path.join(base, file)) ||
        fs.readFileSync(path.join(base, file), 'utf8') !== content,
    )
    .map(([file]) => file);
  if (stale.length) throw Error(`stale contracts: ${stale.join(', ')}`);
}
export async function buildContracts(
  check = false,
  configOnly = false,
): Promise<void> {
  // A cold checkout can generate the config helper before importing routes
  // which consume it. No runtime facade or hand-authored validator is needed.
  const outputs = configOnly ? configOutputs() : await contractOutputs();
  if (check) assertContractFreshness(outputs);
  for (const [file, content] of Object.entries(outputs)) {
    const target = path.join(root, file);
    if (!check) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, content);
    }
  }
  console.log(
    check
      ? 'contracts freshness: pass'
      : `contracts generated: ${Object.keys(outputs).length} files`,
  );
}
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  buildContracts(
    process.argv.includes('--check'),
    process.argv.includes('--config-only'),
  ).catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
